bw_reading/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import speed_reading

urlpatterns = [
    # Examples:
    # url(r'^$', 'bw_reading.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^speed_reading/',
        include('speed_reading.urls',namespace='speed_reading')),
    url(r'(.*?)', 'speed_reading.views.lost', name='speed_reading_lost')
]

speed_reading/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'bw_reading.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^index/$', views.index, name="index"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^login_attempt/$', views.login_attempt, name="login_attempt"),
    url(r'^(?P<passage_id>[0-9]+)/practice/$', views.practice, name="practice"),
    url(r'^save_attempt/$',
        views.save_attempt, name="save_attempt"),
    url(r'^attempt_history/$', views.attempt_history, name="attempt_history"),
]

speed_reading/models.py
from django.contrib.auth.models import User
from django.db import models

class Passage(models.Model):
    """
    This corresponds to a reading passage that the user may attempt.
    """
    passage_title = models.CharField(default="", max_length=200)
    passage_text = models.TextField()
    words_in_passage = models.IntegerField(default=0, editable=False)

    def __str__(self):
        return self.passage_title

    def save(self, *args, **kwargs):
        """
        This overrides the default save method, so when this is
        created, words_in_passage gets set.
        """
        self.words_in_passage = self.count_words(self.passage_text)
        super(Passage, self, *args).save()

    def count_words(self, passage_string):
        """
        Utility method to count the number of words.
        """
        split = passage_string.split()
        return len(split)


class Attempt(models.Model):
    SECONDS_PER_MINUTE = 60
    MILLISECONDS_PER_SECOND = 1000
    """
    A new Attempt is made each time a user clicks start and then stop
    on a passage.
    """
    passage = models.ForeignKey(Passage)
    user = models.ForeignKey(User)
    # Django 1.7 doesn't support 1.8's DurationField:
    duration_in_milliseconds = models.BigIntegerField()
    time_of_occurrence = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + ": " + str(self.words_per_minute) + " wpm"

    @property
    def words_per_minute(self):
        """
        Calculates reading speed of the attempt in words per minute.
        """
        return (self.passage.words_in_passage
                * self.SECONDS_PER_MINUTE 
                * self.MILLISECONDS_PER_SECOND
                / self.duration_in_milliseconds)

speed_reading/views.py
import json

from django.contrib.auth import (
    authenticate, login as auth_login, logout as auth_logout)
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt


from .models import Passage, Attempt


@login_required
def index(request):
    """
    This function handles a homepage-ish view.
    """
    passage_list = Passage.objects.all()
    context = {'passage_list': passage_list}
    return render(request, 'speed_reading/index.html', context)

def login(request, context={}):
    return render(request, 'speed_reading/login.html', context)

def logout(request):
    auth_logout(request)
    return login(
        request, context={"error_message" : "You have been logged out."})


def login_attempt(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            return HttpResponseRedirect(reverse('speed_reading:index'))
        else:
            return login(
                request, context={"error_message" : "Inactive account."})
    else:
        return login(
            request, context={"error_message" : "Invalid account."})


@login_required
def practice(request, passage_id):
    """
    This handles the app/widget view.
    """
    passage = get_object_or_404(Passage, pk=passage_id)
    context = {'passage' : passage}
    return render(request, 'speed_reading/practice.html', context)


@login_required
@csrf_exempt
def save_attempt(request):
    """
    Handles the ajax call to save an attempt.
    """
    passage_id = int(request.POST.get("passage_id"))
    passage = get_object_or_404(Passage, pk=passage_id)
    user = request.user
    duration = int(request.POST.get("duration"))

    new_attempt = Attempt(passage=passage,
                          user=user,
                          duration_in_milliseconds=duration)
    new_attempt.save()
    return HttpResponse("thanks")

@login_required
@csrf_exempt
def attempt_history(request):
    user = request.user
    passage_id = request.POST.get("passage_id")
    attempts = Attempt.objects.filter(user=user);
    print(attempts)
    data = [[a.words_per_minute for a in attempts], 
            [a.passage.id for a in attempts]];
    print(data)
    return HttpResponse(json.dumps(data));

def lost(request, err):
    return login(
        request, context={
        "error_message" : "That url doesn't exist.  Try logging in?"})

speed_reading/templates/speed_reading/index.html
{% if passage_list %}
    <ul>
    {% for passage in passage_list %}
        <li><a href="/speed_reading/{{ passage.id }}/practice/">{{ passage.passage_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No passages are available.</p>
{% endif %}

speed_reading/templates/speed_reading/login.html
<h1>{{ login }}</h1>
<ul>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'speed_reading:login_attempt' %}" method="post">
{% csrf_token %}
    <input type="text" name="username" id="username">
    <input type="password" name="password" id="password">

<input type="submit" value="submit" />
</form>

speed_reading/templates/speed_reading/practice.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'speed_reading/style.css' %}" />


<body>

<div class="container-fluid">
<div class="row-fluid">
    <div class="col-md-7">
        <div class="row-fluid">

            <div id="lines-div" class="col-md-6">
                <p>
                    Distance of lines from margin:
                </p>
                <input type="text" value="0" class="dial">
            </div>

            <div id="timer-div" class="col-md-6" ng-app="time">
                <timer></timer>
                <input type="hidden" name="passage_id" id="passage_id" value="{{ passage.id }}" />
            </div>
        </div>
        <div class="row-fluid">
            <div id="chart-div" class="col-md-12">
                <button hidden id="attempt-history">request attempt history</button>
                <br>
                <canvas id="chart" width="600" height="350"></canvas>
            </div>
        </div>
    </div>
    <div id="passage-text" class="col-md-5">
        <h1>{{ passage.passage_title }}</h1>
        <h3>Some Explanation of the Rules</h3>
            <div class="row">
                <div class="col-md-9">
                    <div id="wrapper">
                       <canvas id="lines-canvas"> </canvas>
                       <div id="text"> {{ passage.passage_text }} </div>
                    </div>
                </div>

                <div class="col-md-3"></div>
        </div>
</div>
</div>



</body>

<script src="{% static 'jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'jquery.knob.js' %}"></script>
<script src="{% static 'Chart.js' %}"></script>
<script src="{% static 'bootstrap.js' %}"></script>
<script src="{% static 'angular.min.js' %}"></script>
<script src="{% static 'speed_reading/main.js' %}"></script>


</html>